### ISSUE TITLE
安装部署后报错SyntaxError: unterminated string literal (detected at line 146)

### ISSUE THREAD

**Issue by xiih** [SamuNatsu/nonebot-plugin-avalon#1]
09-11 12:12:54 [ERROR] nonebot | Failed to import "nonebot_plugin_avalon"
Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "/home/vm/mio-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/home/vm/mio-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "/home/vm/mio-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 203, in load_all_plugins
    return set(
  File "/home/vm/mio-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/home/vm/mio-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/vm/mio-bot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/vm/mio-bot/.venv/lib/python3.10/site-packages/nonebot_plugin_avalon/__init__.py", line 1, in <module>
    from . import matchers as _
  File "/home/vm/mio-bot/.venv/lib/python3.10/site-packages/nonebot_plugin_avalon/matchers.py", line 1, in <module>
    from .game import Game
  File "/home/vm/mio-bot/.venv/lib/python3.10/site-packages/nonebot_plugin_avalon/game/__init__.py", line 1, in <module>
    from .game import Game as Game
  File "/home/vm/mio-bot/.venv/lib/python3.10/site-packages/nonebot_plugin_avalon/game/game.py", line 146
    f"❓任务情况：{
    ^
SyntaxError: unterminated string literal (detected at line 146)
![屏幕截图 2024-09-11 121315](https://github.com/user-attachments/assets/673f187d-a188-474b-a442-016efd2c49c2)
[](url)

**Comment by SamuNatsu** [comment]
请告诉我你的完整运行环境信息，包括 OS 版本、Python 版本、Nonebot 版本等

以及你使用的部署方式

**Comment by xiih** [comment]
你好。
ubuntu 22.04
Python版本为 3.10.12
Nonebot2版本为2.3.3
使用nb-cli安装：nb plugin install nonebot-plugin-avalon
也尝试过卸载后重新用pip安装，出现一样的报错

**Comment by ATTomatoo** [comment]
我也同样的问题
ubuntu 20.04
python 3.10.10
nonebot 2.1.3
使用pip 安装/还有 直接拖进插件文件夹，同样的报错

这是错误的log
[2024-09-13.log](https://github.com/user-attachments/files/16992412/2024-09-13.log)
[error_2024-09-13.log](https://github.com/user-attachments/files/16992413/error_2024-09-13.log)
错误的截图
![4K}515BC$~JG(K~XT}M}O47](https://github.com/user-attachments/assets/c48f596b-1057-4a6d-ba0d-4ef63b203a98)

**Comment by SamuNatsu** [comment]
大概感觉知道是什么问题了

我用的这种 f-string 写法在 Python 3.12 之后的版本才被采用

现在有两种选择，一种是提升插件 Python 版本约束，二是我想办法扁平化一下现有的 f-string 来适配 3.12 之前的版本

你们看看要选哪种

**Comment by ATTomatoo** [comment]
我这机器人不支持3.12，还得幸苦作者大大适配一下3.12之前的

**Comment by SamuNatsu** [comment]
v0.2.2 已发布 PYPI，请更新尝试，如仍有 `SyntaxError: unterminated string literal` 问题请在这里继续提出，否则 3 天后我将关闭该 issue

其他问题请新开 issue

**Comment by xiih** [comment]
更新后正常运行。辛苦了
